In [1]:
import numpy as np
import pandas as pd

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

# pandas 데이터 파악과 조작

**분석할 데이터를 수집(확보)하면 데이터의 특징을 파악하고 다루기 쉽게 변형하는 작업을 수행해야 한다**

# #2. 데이터 조작

- 데이터 개수 세기
- 데이터 정렬
- 데이터 집계 : 합계, 평균, 최대, 최소
- 데이터 삭제
- 결측치 처리
- 데이터 변경 : 자료형 변경 / 수치형 데이터를 범주형 데이터로 변경

## 4. 데이터 삭제

- **Series.drop**(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')

- **DataFrame.drop**(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')

### 1) 데이터프레임의 행 삭제

- df.drop(labels='행이름', axis=0) : 행삭제 


- 행삭제 후 데이터프레임으로 결과 반환
     
     
- 원본에 반영되지 않으므로 원본수정하려면 저장해야 함
    - 객체변수로 저장하거나, 매개변수 inplace를 True로 지정

In [10]:
np.random.seed(1)
df2 = pd.DataFrame(np.random.randint(10, size=(4,8)))
df2['합계']=df2.sum(axis=1)
df2.loc['col_sum']=df2.sum()
df2

0   1   2   3   4   5  6   7   합계
0         5   8   9   5   0   0  1   7   35
1         6   9   2   4   5   2  4   2   34
2         4   7   7   9   1   7  0   6   41
3         9   9   7   6   9   1  0   1   42
col_sum  24  33  25  24  15  10  5  16  152

- df2의 ColTol 행 삭제

In [11]:
# df2.drop(labels='col_sum', axis=0, inplace=True)
df2= df2.drop(labels='col_sum', axis=0)
df2

0  1  2  3  4  5  6  7  합계
0  5  8  9  5  0  0  1  7  35
1  6  9  2  4  5  2  4  2  34
2  4  7  7  9  1  7  0  6  41
3  9  9  7  6  9  1  0  1  42

### 2) 데이터프레임의 열 삭제
- df.drop(labels='행이름', axis=1) : 열 삭제
- 행삭제 후 데이터프레임으로 결과 반환

In [12]:
df2 = df2.drop(labels='합계', axis=1)
df2

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

-----------------------------------

## 5. 결측치 처리

: **NaN 값 처리** 함수

- **df.dropna(axis=0 또는 1, inplace=False)**
    - NaN값이 있는 열 또는 행을 삭제
    - 원본 반영되지 않음
    - inplace=True : 원본 데이터프레임 변경


- **df.fillna(0, inplace=False)**
    - NaN값을 정해진 숫자로 채움
    - 원본 반영 되지 않음

#### 결측치 적용

In [18]:
np.random.seed(10)
df3 = pd.DataFrame(np.random.randint(10, size=(4,8)))
df3

0  1  2  3  4  5  6  7
0  9  4  0  1  9  0  1  8
1  9  0  8  6  4  3  0  4
2  6  8  1  8  4  1  3  6
3  5  3  9  6  9  1  9  4

In [19]:
df3.iloc[0,0]=np.nan
df3.iloc[2,3]=np.nan
df3.iloc[1,2]=np.nan
df3

0  1    2    3  4  5  6  7
0  NaN  4  0.0  1.0  9  0  1  8
1  9.0  0  NaN  6.0  4  3  0  4
2  6.0  8  1.0  NaN  4  1  3  6
3  5.0  3  9.0  6.0  9  1  9  4

### 1) 결측치 포함 행 삭제 : dropna()

In [20]:
df3.dropna()
df3

0  1    2    3  4  5  6  7
3  5.0  3  9.0  6.0  9  1  9  4

0  1    2    3  4  5  6  7
0  NaN  4  0.0  1.0  9  0  1  8
1  9.0  0  NaN  6.0  4  3  0  4
2  6.0  8  1.0  NaN  4  1  3  6
3  5.0  3  9.0  6.0  9  1  9  4

### 2) 결측치 포함 열 삭제 : dropna(axis=1)

In [17]:
df3.dropna(axis=1)
df3

1  2  4  5  6  7
0  4  0  9  0  1  8
1  0  8  4  3  0  4
2  8  1  4  1  3  6
3  3  9  9  1  9  4

0  1  2    3  4  5  6  7
0  NaN  4  0  1.0  9  0  1  8
1  9.0  0  8  6.0  4  3  0  4
2  6.0  8  1  NaN  4  1  3  6
3  5.0  3  9  6.0  9  1  9  4

### 3) 결측치를 다른 값으로 대체 : fillna() 함수

**결측치를 0으로 변경**

In [21]:
df3.fillna(0)

0  1    2    3  4  5  6  7
0  0.0  4  0.0  1.0  9  0  1  8
1  9.0  0  0.0  6.0  4  3  0  4
2  6.0  8  1.0  0.0  4  1  3  6
3  5.0  3  9.0  6.0  9  1  9  4

In [25]:
df3[0].fillna(0)
df3

0    0.0
1    9.0
2    6.0
3    5.0
Name: 0, dtype: float64

0  1    2         3  4  5  6  7
0  NaN  4  0.0  1.000000  9  0  1  8
1  9.0  0  NaN  6.000000  4  3  0  4
2  6.0  8  1.0  4.333333  4  1  3  6
3  5.0  3  9.0  6.000000  9  1  9  4

**결측치를 1로 변경**

In [22]:
df3.fillna(1)

0  1    2    3  4  5  6  7
0  1.0  4  0.0  1.0  9  0  1  8
1  9.0  0  1.0  6.0  4  3  0  4
2  6.0  8  1.0  1.0  4  1  3  6
3  5.0  3  9.0  6.0  9  1  9  4

In [24]:
df3[2].fillna(1)

0    0.0
1    1.0
2    1.0
3    9.0
Name: 2, dtype: float64

#### 결측치를 평균값으로 대체

In [23]:
df3[3].fillna(df3[3].mean(), inplace=True)
df3

0  1    2         3  4  5  6  7
0  NaN  4  0.0  1.000000  9  0  1  8
1  9.0  0  NaN  6.000000  4  3  0  4
2  6.0  8  1.0  4.333333  4  1  3  6
3  5.0  3  9.0  6.000000  9  1  9  4

#### 결측치 확인

In [27]:
df3.isna().sum()

0    1
1    0
2    1
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [28]:
titanic = pd.read_csv('data/titanic.csv')
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [30]:
# 데이터프레임의 컬럼별 결측치 개수 확인
titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

-------------------------------

## 6. 데이터의 변경

### 1) 데이터 자료형(dtype) 변경


**astype(데이터형)**

In [31]:
df3

0  1    2         3  4  5  6  7
0  NaN  4  0.0  1.000000  9  0  1  8
1  9.0  0  NaN  6.000000  4  3  0  4
2  6.0  8  1.0  4.333333  4  1  3  6
3  5.0  3  9.0  6.000000  9  1  9  4

#### 데이터를 정수형으로 변경 : astype(int)

In [36]:
df3.fillna(0).astype(int)

0  1  2  3  4  5  6  7
0  0  4  0  1  9  0  1  8
1  9  0  0  6  4  3  0  4
2  6  8  1  4  4  1  3  6
3  5  3  9  6  9  1  9  4

In [37]:
# 지정된 컬럼의 데이터형식을 변경 {}
df3.astype({3:'int64'})

0  1    2  3  4  5  6  7
0  NaN  4  0.0  1  9  0  1  8
1  9.0  0  NaN  6  4  3  0  4
2  6.0  8  1.0  4  4  1  3  6
3  5.0  3  9.0  6  9  1  9  4

#### 데이터를 실수형으로 변경 : astype(float)

In [33]:
df3.astype(float)

0    1    2         3    4    5    6    7
0  NaN  4.0  0.0  1.000000  9.0  0.0  1.0  8.0
1  9.0  0.0  NaN  6.000000  4.0  3.0  0.0  4.0
2  6.0  8.0  1.0  4.333333  4.0  1.0  3.0  6.0
3  5.0  3.0  9.0  6.000000  9.0  1.0  9.0  4.0

### 2) 수치형 데이터를 범주형 데이터로 변환

- 범주형 데이터 **Categorical 클래스** 객체로 변환


- **cut(data, bins, label)** : 구간 경계선을 선정하여 범주형 데이터로 변환
    - data : 구간 나눌 실제 값
    - bins : 구간 경계값
    - label: 카테고리 값
        
        
- **qcut(data, bins, label)** : 구간 경계선을 선정하지 않고 데이터 개수가 같도록 구간을 분할하여 범주형 데이터로 변환

### ① 구간 경계선을 선정하여 범주형 데이터로 변환 : cut()

#### 리스트 데이터를 범주형 데이터로 변환

- 예제 데이터

In [45]:
ages = [0.1,0.5,5,4,6,3,10,31,15,33,37,17,25,36,70,61,20,40,31,100]
len(ages)

20

- 구간 경계값, 범주 라벨 설정

In [46]:
# 0 < 영유아 <= 5
# 5 < 미성년자 <=15
# 15 < 청소년 <= 20
# 20 < 청년 <= 40
# 40 < 장년 <= 64
# 64 < 노년 <= 100

# 구간경계값
bins = [0, 5, 15, 20, 40, 64, 100]

# 구간별(범주) 라벨
labels = ['영유아', '미성년자', '청소년', '청년', '장년', '노년']

- cut()로 범주형 데이터로 변경

In [47]:
cut_ages = pd.cut(ages, bins=bins, labels=labels)
cut_ages

['영유아', '영유아', '영유아', '영유아', '미성년자', ..., '장년', '청소년', '청년', '청년', '노년']
Length: 20
Categories (6, object): ['영유아' < '미성년자' < '청소년' < '청년' < '장년' < '노년']

In [49]:
type(cut_ages)

pandas.core.arrays.categorical.Categorical

In [48]:
list(cut_ages)

['영유아',
 '영유아',
 '영유아',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '청년',
 '미성년자',
 '청년',
 '청년',
 '청소년',
 '청년',
 '청년',
 '노년',
 '장년',
 '청소년',
 '청년',
 '청년',
 '노년']

In [53]:
df_age['나이대'].value_counts()

청년      7
영유아     5
미성년자    3
청소년     2
노년      2
장년      1
Name: 나이대, dtype: int64

In [54]:
df_age.나이.min()
df_age.나이.max()
df_age.나이.mean()

0.1

100.0

27.23

In [55]:
df_age.describe()

나이
count   20.000000
mean    27.230000
std     25.948128
min      0.100000
25%      5.750000
50%     22.500000
75%     36.250000
max    100.000000

In [56]:
df_age.describe(include='all')

나이  나이대
count    20.000000   20
unique         NaN    6
top            NaN   청년
freq           NaN    7
mean     27.230000  NaN
std      25.948128  NaN
min       0.100000  NaN
25%       5.750000  NaN
50%      22.500000  NaN
75%      36.250000  NaN
max     100.000000  NaN

**참고: Categorical 클래스 객체**

- 카테고리명 속성 : Categorical.categories


- 코드 속성 : Categorical.codes 
    - 인코딩한 카테고리 값을 정수로 갖음

In [57]:
cut_ages.categories

Index(['영유아', '미성년자', '청소년', '청년', '장년', '노년'], dtype='object')

In [59]:
ages
cut_ages.codes

[0.1, 0.5, 5, 4, 6, 3, 10, 31, 15, 33, 37, 17, 25, 36, 70, 61, 20, 40, 31, 100]

array([0, 0, 0, 0, 1, 0, 1, 3, 1, 3, 3, 2, 3, 3, 5, 4, 2, 3, 3, 5],
      dtype=int8)

#### 데이터프레임 데이터를 범주형으로 변환

- ages 리스트를 데이터프레임으로 변경

In [61]:
df_age = pd.DataFrame(ages, columns=['나이'])
df_age.head()

나이
0  0.1
1  0.5
2  5.0
3  4.0
4  6.0

- 데이터프레임에 범주형 데이터 추가

In [60]:
df_age['나이대']=cut_ages
df_age.head()

나이   나이대
0  0.1   영유아
1  0.5   영유아
2  5.0   영유아
3  4.0   영유아
4  6.0  미성년자

### ② 데이터 개수가 같도록 데이터 분할 :  qcut()

**: 구간 경계선을 지정하지 않고 데이터의 사분위수(quantile) 기준으로 분할**

- 형식 : **pd.qcut(data,구간수,labels=[d1,d2....])**


- 예. 1000개의 데이터를 4구간으로 나누려고 한다면
     - qcut 명령어를 사용 한 구간마다 250개씩 나누게 된다.
     - 예외) 같은 숫자인 경우에는 같은 구간으로 처리한다.

- 예제 데이터

In [63]:
# 정수난수 20개
np.random.seed(2)
data = np.random.randint(20, size=20)
data

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11])

- 20개의 데이터를 동일한 개수를 갖는 4개 구간으로 나누어 범주형 데이터로 생성하고, 각 구간의 label은 Q1,Q2,Q3,Q4 로 설정

In [64]:
qcut_data = pd.qcut(data, 4, labels=['q1', 'q2', 'q3', 'q4'])
qcut_data

['q2', 'q4', 'q4', 'q2', 'q3', ..., 'q1', 'q1', 'q1', 'q3', 'q3']
Length: 20
Categories (4, object): ['q1' < 'q2' < 'q3' < 'q4']

In [65]:
list(qcut_data)

['q2',
 'q4',
 'q4',
 'q2',
 'q3',
 'q4',
 'q3',
 'q2',
 'q2',
 'q1',
 'q4',
 'q3',
 'q4',
 'q1',
 'q2',
 'q1',
 'q1',
 'q1',
 'q3',
 'q3']

In [66]:
data
np.sort(data)

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11])

array([ 2,  3,  4,  5,  6,  7,  7,  8,  8,  8, 10, 11, 11, 11, 11, 13, 15,
       15, 17, 18])

In [69]:
df_data = pd.DataFrame(data, columns=['data'])
df_data

data
0      8
1     15
2     13
3      8
4     11
5     18
6     11
7      8
8      7
9      2
10    17
11    11
12    15
13     5
14     7
15     3
16     6
17     4
18    10
19    11

In [70]:
df_data['qcut'] = qcut_data
df_data

data qcut
0      8   q2
1     15   q4
2     13   q4
3      8   q2
4     11   q3
5     18   q4
6     11   q3
7      8   q2
8      7   q2
9      2   q1
10    17   q4
11    11   q3
12    15   q4
13     5   q1
14     7   q2
15     3   q1
16     6   q1
17     4   q1
18    10   q3
19    11   q3

In [71]:
qcut_data.categories

Index(['q1', 'q2', 'q3', 'q4'], dtype='object')

In [73]:
data
qcut_data.codes

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11])

array([1, 3, 3, 1, 2, 3, 2, 1, 1, 0, 3, 2, 3, 0, 1, 0, 0, 0, 2, 2],
      dtype=int8)