In [1]:
import numpy as np
import pandas as pd

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

# pandas 다중 인덱스(multi index)

- 행이나 열 인덱스가 계층으로 구성된 인덱스(Hierarchical indexing)

In [4]:
df = pd.DataFrame([[1,2,3,4],[2,3,4,6]],
                 index =['a b'.split()])
df

0  1  2  3
a  1  2  3  4
b  2  3  4  6

In [5]:
df.index

MultiIndex([('a',),
            ('b',)],
           )

In [6]:
df.loc['a']

0  1  2  3
a  1  2  3  4

### 참고. 난수 생성 : np.random 모듈


##### np.random.seed(seed값)

- seed : 난수 알고리즘에서 사용하는 기본 값
    - seed 값이 같으면 동일한 난수 발생
    - 예. np.random.seed(10) 


- 계속 변경되는 난수를 생성하려면 시드값이 매번 변하도록 지정
    - 예. np.random.seed(int(time.time()))
    

#### 난수 생성 함수

- random.rand() : 주어진 형태의 난수 배열 생성
- random.randint(최소값, 최대값, size=n) 
    - [최소값, 최대값)의 범위에서 임의의 정수 생성
    
- random.randn() : 표준정규분포(Standard normal distribution)로부터 샘플링된 난수 생성

- random.standard_normal() : 표준정규분포 난수 발생

- random.normal([loc, scale, size]) : 정규분포 난수 생성

- random.random_sample(size) : [0,1)사이의 난수 생성

- random.choice(a[, size, replace, p]) : 주어진 배열로 부터 표본추출

In [7]:
# 고정시드값
np.random.seed(10)
np.random.randint(5, size=4)

array([1, 4, 0, 1])

In [8]:
np.random.randint(5, size=4)

array([3, 4, 1, 0])

In [9]:
import time

int(time.time())

1675298930

In [10]:
time.time()

1675298942.6659155

In [11]:
# 변경시드값
np.random.seed(int(time.time()))
np.random.randint(5, size=4)

array([3, 1, 0, 1])

In [12]:
np.random.randint(5, size=4)

array([3, 4, 4, 2])

### 참고. 파이썬의 random 모듈

: https://docs.python.org/ko/3/library/random.html


#### 정수 난수 발생 함수

##### random.randrange(start, stop[, step])
- range(start, stop, step)에서 임의로 선택된 요소를 반환
- choice(range(start, stop, step))와 동등하지만 실제로 range 객체를 만들지는 않음

##### random.randint(a, b)
- `a <= N <= b` 를 만족하는 임의의 정수 N을 반환
- randrange(a, b+1)의 별칭

#### 시퀀스 난수 발생 함수
##### random.choice(seq)
- 비어 있지 않은 시퀀스 seq에서 임의의 요소를 반환
- seq가 비어 있으면, IndexError를 발생


##### random.choices(population, weights=None, *, cum_weights=None, k=1)
- population에서 중복을 허락하면서(with replacement) 선택한 k 크기의 요소 리스트를 반환
- population이 비어 있으면 IndexError 발생
- weights 시퀀스가 지정되면 상대 가중치에 따라 선택됨
- weights나 cum_weights를 지정하지 않으면 같은 확률로 선택
- weights 시퀀스가 제공되면, population 시퀀스와 길이가 같아야 함
- weights와 cum_weights를 모두 지정하는 것은 TypeError

##### random.sample(population, k, *, counts=None)
- population 시퀀스로부터 추출한 k개 길이의 새 리스트를 반환
- random sampling without replacement

#### 실수 난수 발생 함수
##### random.random()
- `0.0 <= X < 1.0` 사이의 실수 반환

##### random.uniform(a, b)
- `a <= b` 일 때 `a <= N <= b`, `b < a` 일 때 `b <= N <= a`를 만족하는 임의의 부동 소수점 숫자 N을 반환
- 종단 값 b는 방정식 a + (b-a) * random()의 부동 소수점 자리 올림에 따라 범위에 포함되거나 포함되지 않을 수 있음

### 1. 다중인덱스를 갖는 Series

#### 예1. 난수 데이터를 갖는 Series

In [14]:
index = [np.array(["bar", "bar", "baz", "baz",
                    "foo", "foo", "qux", "qux"]),
          np.array(["one", "two", "one", "two",
                    "one", "two", "one", "two"])]
index

[array(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
       dtype='<U3'),
 array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'],
       dtype='<U3')]

In [15]:
s1=pd.Series(np.random.randn(8),
            index = index)
s1

bar  one   -1.682615
     two   -0.608805
baz  one   -0.786653
     two   -0.341528
foo  one    0.260367
     two    1.602779
qux  one    0.613140
     two   -0.124383
dtype: float64

In [16]:
s1.index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           )

#### 예2. 키를 튜플로 갖는 딕셔너리의 데이터로 Series 생성

In [17]:
# 키를 튜플로 갖는 딕셔너리 데이터
data = {('James', 'Eng'): 100,
        ('James', 'Math') : 90,
        ('Ted', 'Eng') : 90,
        ('Ted', 'Math') : 70,
        ('Adam', 'Eng') : 85,
        ('Adam', 'Math') : 90 }
data

{('James', 'Eng'): 100,
 ('James', 'Math'): 90,
 ('Ted', 'Eng'): 90,
 ('Ted', 'Math'): 70,
 ('Adam', 'Eng'): 85,
 ('Adam', 'Math'): 90}

In [18]:
s2=pd.Series(data=data)
s2

James  Eng     100
       Math     90
Ted    Eng      90
       Math     70
Adam   Eng      85
       Math     90
dtype: int64

In [19]:
s2.index

MultiIndex([('James',  'Eng'),
            ('James', 'Math'),
            (  'Ted',  'Eng'),
            (  'Ted', 'Math'),
            ( 'Adam',  'Eng'),
            ( 'Adam', 'Math')],
           )

#### 인덱스의 이름 지정 : 시리즈.index.names = [ , ]

In [20]:
s2.index.names = ['name', 'course']
s2

name   course
James  Eng       100
       Math       90
Ted    Eng        90
       Math       70
Adam   Eng        85
       Math       90
dtype: int64

#### 다중인덱스를 갖는 Series의 인덱싱

- 시리즈[상위인덱스]
- 시리즈.상위인덱스
- 시리즈[(상위인덱스, 하위인덱스)]
- 시리즈.상위인데스,하위인덱스
- 시리즈[:, 하위인덱스]

In [21]:
s2['James']

course
Eng     100
Math     90
dtype: int64

In [22]:
s2.James

course
Eng     100
Math     90
dtype: int64

In [24]:
s2[('Ted', 'Eng')]   # 튜플 형태로 제시

90

In [25]:
s2.Adam.Eng

85

In [26]:
s2[['James', 'Ted']]   # 상위 인덱스끼리는 리스트 사용

name   course
James  Eng       100
       Math       90
Ted    Eng        90
       Math       70
dtype: int64

In [27]:
s2.loc[['James', 'Ted']]

name   course
James  Eng       100
       Math       90
Ted    Eng        90
       Math       70
dtype: int64

In [29]:
s2['James', :]

course
Eng     100
Math     90
dtype: int64

In [30]:
s2[:, 'Eng']

name
James    100
Ted       90
Adam      85
dtype: int64

### 2. 다중 인덱스를 갖는 DataFrame

- 데이터 프레임 생성 시 생성자에서 columns인수나 index 인수를  2차원 리스트(행렬) 형태로 지정할 경우

#### 1) column인덱스를 다중 인덱스로 갖는 DataFrame

In [33]:
np.random.seed(0)
data = np.round(np.random.randn(5, 4), 2)
data

array([[ 1.76,  0.4 ,  0.98,  2.24],
       [ 1.87, -0.98,  0.95, -0.15],
       [-0.1 ,  0.41,  0.14,  1.45],
       [ 0.76,  0.12,  0.44,  0.33],
       [ 1.49, -0.21,  0.31, -0.85]])

In [40]:
df = pd.DataFrame(data=data,
               columns=[['A', 'A', 'B', 'B'],
                      ['C1','C2','C3','C4']])
df

A           B      
     C1    C2    C3    C4
0  1.76  0.40  0.98  2.24
1  1.87 -0.98  0.95 -0.15
2 -0.10  0.41  0.14  1.45
3  0.76  0.12  0.44  0.33
4  1.49 -0.21  0.31 -0.85

#### 열 인덱싱(1): df[상위인덱스]
- 상위 인덱스의 모든 열에 대한 데이터프레임 반환

In [ ]:
df

#### 열 인덱싱(2): df[(상위인덱스, 하위인덱스)]
- 인덱스가 하나가 아니므로 묶어서(튜플로) 전달해야 함
- 시리즈로 반환

In [41]:
df[('B','C3')]

0    0.98
1    0.95
2    0.14
3    0.44
4    0.31
Name: (B, C3), dtype: float64

In [42]:
df['B','C3']

0    0.98
1    0.95
2    0.14
3    0.44
4    0.31
Name: (B, C3), dtype: float64

#### 열인덱싱(3) :  . 연산자로 확장

- df.상위인덱스
- df.상위인덱스.하위인덱스

In [43]:
df.B.C3

0    0.98
1    0.95
2    0.14
3    0.44
4    0.31
Name: C3, dtype: float64

In [44]:
df.A

C1    C2
0  1.76  0.40
1  1.87 -0.98
2 -0.10  0.41
3  0.76  0.12
4  1.49 -0.21

#### 열인덱스 이름 지정 : df.columns.names = []

In [45]:
df.columns.names = ['upper','lower']
df

upper     A           B      
lower    C1    C2    C3    C4
0      1.76  0.40  0.98  2.24
1      1.87 -0.98  0.95 -0.15
2     -0.10  0.41  0.14  1.45
3      0.76  0.12  0.44  0.33
4      1.49 -0.21  0.31 -0.85

#### 2) 행인덱스를 다중 인덱스로 갖는 DataFrame

In [47]:
data2 = np.random.randint(1,10,size=(4,4))
df2 = pd.DataFrame(data=data2,
                  index=[['a','a','b','b'],
                        ['1','2','1','2']],
                  columns=['A','B','C','D'])
df2

A  B  C  D
a 1  5  9  2  2
  2  8  4  7  8
b 1  3  1  4  6
  2  5  5  7  5

In [49]:
df2.index

MultiIndex([('a', '1'),
            ('a', '2'),
            ('b', '1'),
            ('b', '2')],
           )

#### 행인덱싱(1) : df.loc[상위인덱스]

In [50]:
df2.loc['a']

A  B  C  D
1  5  9  2  2
2  8  4  7  8

In [52]:
df2.loc['a':]

A  B  C  D
a 1  5  9  2  2
  2  8  4  7  8
b 1  3  1  4  6
  2  5  5  7  5

#### 행인덱싱(2) : df.loc[(상위인덱스, 하위인덱스)]
- 상위인덱스와 하위인덱스를 튜플로 전달

In [53]:
df2.loc[('a','1')]

A    5
B    9
C    2
D    2
Name: (a, 1), dtype: int32

#### 인덱서 iloc : df.iloc[  ]
- iloc인덱서는 행이름, 열이름 기반이 아님

In [56]:
df2.iloc[0]

A    5
B    9
C    2
D    2
Name: (a, 1), dtype: int32

In [57]:
df2.iloc[1]

A    8
B    4
C    7
D    8
Name: (a, 2), dtype: int32

In [58]:
df2.iloc[1,1:]

B    4
C    7
D    8
Name: (a, 2), dtype: int32

#### 3)  행과 열에 모두 다중인덱스를 갖는 DataFrame

In [59]:
data3 = np.round(np.random.randn(6,4),2)
data3

array([[ 1.25,  1.42, -0.74, -2.52],
       [-1.51,  1.15, -1.19,  1.14],
       [ 1.51,  1.07, -0.69,  0.01],
       [-0.38, -0.04,  0.37, -0.04],
       [-0.3 , -2.22,  0.72,  0.36],
       [ 1.08,  0.19,  0.85,  0.02]])

In [60]:
# col1 = ['A','A','B','B']
col1 = ['A']*2 + ['B']*2
col2 = ['C'+str(i) for i in range(1,5)]
col1
col2

['A', 'A', 'B', 'B']

['C1', 'C2', 'C3', 'C4']

In [62]:
idx1 = ['M']*3 +['F']*3
idx2 = ['id'+str(i) for i in range(1,4)]*2
idx1
idx2

['M', 'M', 'M', 'F', 'F', 'F']

['id1', 'id2', 'id3', 'id1', 'id2', 'id3']

In [64]:
df3 = pd.DataFrame(data=data3,
                  index=[idx1, idx2],
                  columns=[col1,col2])
df3

A           B      
         C1    C2    C3    C4
M id1  1.25  1.42 -0.74 -2.52
  id2 -1.51  1.15 -1.19  1.14
  id3  1.51  1.07 -0.69  0.01
F id1 -0.38 -0.04  0.37 -0.04
  id2 -0.30 -2.22  0.72  0.36
  id3  1.08  0.19  0.85  0.02

#### 행/열 각 인덱스에 이름(names) 설정

- 이름을 지정하면 직관성이 높아지고 편리하게 사용할 수 있음
- 열이름/행이름 구분하는데 용이
- 문법
    - df.columns.names = 값 또는 리스트
    - df.index.names = 값 또는 리스트

In [65]:
df3.columns.names=['Cidx1','Cidx2']
df3.index.names=['Ridx1','Ridx2']
df3

Cidx1           A           B      
Cidx2          C1    C2    C3    C4
Ridx1 Ridx2                        
M     id1    1.25  1.42 -0.74 -2.52
      id2   -1.51  1.15 -1.19  1.14
      id3    1.51  1.07 -0.69  0.01
F     id1   -0.38 -0.04  0.37 -0.04
      id2   -0.30 -2.22  0.72  0.36
      id3    1.08  0.19  0.85  0.02

In [66]:
df3.index

MultiIndex([('M', 'id1'),
            ('M', 'id2'),
            ('M', 'id3'),
            ('F', 'id1'),
            ('F', 'id2'),
            ('F', 'id3')],
           names=['Ridx1', 'Ridx2'])

In [67]:
df3.columns

MultiIndex([('A', 'C1'),
            ('A', 'C2'),
            ('B', 'C3'),
            ('B', 'C4')],
           names=['Cidx1', 'Cidx2'])

### 3. MultiIndex 객체
- https://pandas.pydata.org/docs/user_guide/advanced.html

- 생성 방법
1. MultiIndex.from_arrays() 사용 : 배열(array)의 리스트
2. MultiIndex.from_tuples() : 튜플들(tuples)의 리스트
3. MultiIndex.from_product() : 리스트의 cross product
4. MultiIndex.from_frame() : DataFrame

In [68]:
# 1. MultiIndex.from_arrays() 이용한 다중인덱스 생성

arrays = np.array([["one", "two", "one", "two"],
                   ["bar", "baz", "foo", "qux"]])
arrays

index = pd.MultiIndex.from_arrays(arrays, 
                                  names=["first", "second"])
index

array([['one', 'two', 'one', 'two'],
       ['bar', 'baz', 'foo', 'qux']], dtype='<U3')

MultiIndex([('one', 'bar'),
            ('two', 'baz'),
            ('one', 'foo'),
            ('two', 'qux')],
           names=['first', 'second'])

In [69]:
# 2. MultiIndex.from_tuples() 이용한 다중인덱스 생성

arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"]]

tuples = list(zip(*arrays))
tuples

index = pd.MultiIndex.from_tuples(tuples, 
                                  names=["first", "second"])
index

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [70]:
# 3. MultiIndex.from_product() 사용한 다중인덱스 생성

iterables = [["bar", "baz", "foo", "qux"], ["one", "two"]]
pd.MultiIndex.from_product(iterables,
                           names=["first", "second"])

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [72]:
# 4. MultiIndex.from_frame()를 사용한 다중인덱스 생성

df = pd.DataFrame([["bar", "one"], ["bar", "two"],
                   ["foo", "one"], ["foo", "two"]],
                  columns=["first", "second"])
df
pd.MultiIndex.from_frame(df)

first second
0   bar    one
1   bar    two
2   foo    one
3   foo    two

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('foo', 'one'),
            ('foo', 'two')],
           names=['first', 'second'])

#### 예제. MultiIndex객체 생성하여 다중인덱스 설정

In [73]:
data4 = np.round(np.random.randn(4,9),2)
index = pd.MultiIndex.from_product([[1995, 2000], ['May','Dec']],
                                  names = ['year','month'])
index
columns = pd.MultiIndex.from_product([['A','B','C'],[1,2,3]],
                                    names = ['name','count'])
columns
df4 = pd.DataFrame(data=data4,
                  index=index,
                  columns=columns)
df4

MultiIndex([(1995, 'May'),
            (1995, 'Dec'),
            (2000, 'May'),
            (2000, 'Dec')],
           names=['year', 'month'])

MultiIndex([('A', 1),
            ('A', 2),
            ('A', 3),
            ('B', 1),
            ('B', 2),
            ('B', 3),
            ('C', 1),
            ('C', 2),
            ('C', 3)],
           names=['name', 'count'])

name           A                 B                 C            
count          1     2     3     1     2     3     1     2     3
year month                                                      
1995 May    0.43  1.00 -0.49  0.71  1.11 -2.15 -0.42 -1.07  0.22
     Dec   -1.12 -1.05  1.01  1.54 -0.40  0.86 -0.23  0.81  0.29
2000 May   -0.54  1.91 -0.48  1.44 -1.15  0.81  1.76  0.97 -1.55
     Dec    0.19  1.60 -1.42 -2.44 -2.06 -0.99  1.01  1.40 -0.65

In [74]:
df4.reset_index()

name   year month     A                 B                 C            
count                 1     2     3     1     2     3     1     2     3
0      1995   May  0.43  1.00 -0.49  0.71  1.11 -2.15 -0.42 -1.07  0.22
1      1995   Dec -1.12 -1.05  1.01  1.54 -0.40  0.86 -0.23  0.81  0.29
2      2000   May -0.54  1.91 -0.48  1.44 -1.15  0.81  1.76  0.97 -1.55
3      2000   Dec  0.19  1.60 -1.42 -2.44 -2.06 -0.99  1.01  1.40 -0.65

### 4. 다중인덱스의 특정 레벨 제거 : droplevel(level, axis)

#### 1) 시리즈의 다중인덱스 레벨 제거

In [75]:
s2

name   course
James  Eng       100
       Math       90
Ted    Eng        90
       Math       70
Adam   Eng        85
       Math       90
dtype: int64

In [76]:
s2.droplevel(0)

course
Eng     100
Math     90
Eng      90
Math     70
Eng      85
Math     90
dtype: int64

In [78]:
s2.droplevel(1)

name
James    100
James     90
Ted       90
Ted       70
Adam      85
Adam      90
dtype: int64

#### 2) 데이터프레임에서 다중인덱스 레벨 제거

In [79]:
df4

name           A                 B                 C            
count          1     2     3     1     2     3     1     2     3
year month                                                      
1995 May    0.43  1.00 -0.49  0.71  1.11 -2.15 -0.42 -1.07  0.22
     Dec   -1.12 -1.05  1.01  1.54 -0.40  0.86 -0.23  0.81  0.29
2000 May   -0.54  1.91 -0.48  1.44 -1.15  0.81  1.76  0.97 -1.55
     Dec    0.19  1.60 -1.42 -2.44 -2.06 -0.99  1.01  1.40 -0.65

#### 행인덱스 레벨 제거

In [81]:
df4.droplevel(level=0, axis=0)

name      A                 B                 C            
count     1     2     3     1     2     3     1     2     3
month                                                      
May    0.43  1.00 -0.49  0.71  1.11 -2.15 -0.42 -1.07  0.22
Dec   -1.12 -1.05  1.01  1.54 -0.40  0.86 -0.23  0.81  0.29
May   -0.54  1.91 -0.48  1.44 -1.15  0.81  1.76  0.97 -1.55
Dec    0.19  1.60 -1.42 -2.44 -2.06 -0.99  1.01  1.40 -0.65

In [82]:
df4.droplevel(level=1, axis=0)

name      A                 B                 C            
count     1     2     3     1     2     3     1     2     3
year                                                       
1995   0.43  1.00 -0.49  0.71  1.11 -2.15 -0.42 -1.07  0.22
1995  -1.12 -1.05  1.01  1.54 -0.40  0.86 -0.23  0.81  0.29
2000  -0.54  1.91 -0.48  1.44 -1.15  0.81  1.76  0.97 -1.55
2000   0.19  1.60 -1.42 -2.44 -2.06 -0.99  1.01  1.40 -0.65

#### 열인덱스 레벨 제거

In [83]:
df4.droplevel(level=0, axis=1)

count          1     2     3     1     2     3     1     2     3
year month                                                      
1995 May    0.43  1.00 -0.49  0.71  1.11 -2.15 -0.42 -1.07  0.22
     Dec   -1.12 -1.05  1.01  1.54 -0.40  0.86 -0.23  0.81  0.29
2000 May   -0.54  1.91 -0.48  1.44 -1.15  0.81  1.76  0.97 -1.55
     Dec    0.19  1.60 -1.42 -2.44 -2.06 -0.99  1.01  1.40 -0.65

In [84]:
df4.droplevel(level=1, axis=1)

name           A     A     A     B     B     B     C     C     C
year month                                                      
1995 May    0.43  1.00 -0.49  0.71  1.11 -2.15 -0.42 -1.07  0.22
     Dec   -1.12 -1.05  1.01  1.54 -0.40  0.86 -0.23  0.81  0.29
2000 May   -0.54  1.91 -0.48  1.44 -1.15  0.81  1.76  0.97 -1.55
     Dec    0.19  1.60 -1.42 -2.44 -2.06 -0.99  1.01  1.40 -0.65

### 5. 행인덱스 레벨 해제 : unstack()

: 행인덱스 -> 열인덱스로 변환

#### 1) 시리즈의 다중인덱스 레벨 해제

- 해제된 레벨 인덱스는 열인덱스로 변경되며, 데이터프레임으로 반환됨

In [85]:
s = pd.Series([1, 2, 3, 4],
              index=pd.MultiIndex.from_product([['one', 'two'],
                                                ['a', 'b']]))
s

one  a    1
     b    2
two  a    3
     b    4
dtype: int64

#### 마지막 레벨 해제 : unstack(level=-1)

In [86]:
s.unstack(level=-1)

a  b
one  1  2
two  3  4

#### 첫번째 레벨 해제 : unstack(level=0)

In [88]:
s.unstack(level=0)

one  two
a    1    3
b    2    4

#### 2) 데이터프레임의 다중 행인덱스 레벨 해제

- 데이터프레임의 인덱스 레벨 해제
- 해제된 레벨은 열인덱스 중 가장 마지막 레벨이 됨

[형식] DataFrame.unstack(level=-1, fill_value=None)


- level : int, str, or list of these, default= -1 (last level)
    - Level(s) of index to unstack, can pass level name.

- fill_value : int, str or dict
    - Replace NaN with this value if the unstack produces missing values.


- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html

In [89]:
index = pd.MultiIndex.from_product([[1995, 2000], ['May','Dec']],
                                 names = ['year', 'month'])
columns = pd.MultiIndex.from_product([['A','B','C'],[1,2]],
                                    names = ['name', 'count'])

df =pd.DataFrame(np.round(np.random.randn(4,6), 1),
                  index = index, columns = columns)
df

name          A         B         C     
count         1    2    1    2    1    2
year month                              
1995 May   -0.3 -0.7 -0.5  0.1 -0.5 -0.4
     Dec    0.3 -1.7 -0.9 -0.1 -0.4 -2.1
2000 May    0.0 -0.6  0.5 -0.6 -0.3  1.0
     Dec   -0.0  0.1 -0.6 -0.1  0.7 -0.8

In [90]:
df.unstack(level=0)

name     A                   B                   C               
count    1         2         1         2         1         2     
year  1995 2000 1995 2000 1995 2000 1995 2000 1995 2000 1995 2000
month                                                            
Dec    0.3 -0.0 -1.7  0.1 -0.9 -0.6 -0.1 -0.1 -0.4  0.7 -2.1 -0.8
May   -0.3  0.0 -0.7 -0.6 -0.5  0.5  0.1 -0.6 -0.5 -0.3 -0.4  1.0

In [91]:
df.unstack()

name     A                   B                   C               
count    1         2         1         2         1         2     
month  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May
year                                                             
1995   0.3 -0.3 -1.7 -0.7 -0.9 -0.5 -0.1  0.1 -0.4 -0.5 -2.1 -0.4
2000  -0.0  0.0  0.1 -0.6 -0.6  0.5 -0.1 -0.6  0.7 -0.3 -0.8  1.0

In [92]:
df.unstack(level='month')

name     A                   B                   C               
count    1         2         1         2         1         2     
month  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May
year                                                             
1995   0.3 -0.3 -1.7 -0.7 -0.9 -0.5 -0.1  0.1 -0.4 -0.5 -2.1 -0.4
2000  -0.0  0.0  0.1 -0.6 -0.6  0.5 -0.1 -0.6  0.7 -0.3 -0.8  1.0

In [93]:
df.unstack(level=0)

name     A                   B                   C               
count    1         2         1         2         1         2     
year  1995 2000 1995 2000 1995 2000 1995 2000 1995 2000 1995 2000
month                                                            
Dec    0.3 -0.0 -1.7  0.1 -0.9 -0.6 -0.1 -0.1 -0.4  0.7 -2.1 -0.8
May   -0.3  0.0 -0.7 -0.6 -0.5  0.5  0.1 -0.6 -0.5 -0.3 -0.4  1.0

### 6. 열인덱스 레벨 해제 : stack()

: 열인덱스 -> 행인덱스로 변환

#### 데이터프레임에서 열인덱스 레벨 해제

- 지정한 열인덱스가 행인덱스의 마지막 레벨로 변환 추가됨
- single level 열인덱스를 갖는 경우 시리즈로 반환
- multi level 열인덱스를 갖는 경우 데이터프레임 반환

[형식] DataFrame.stack(level=- 1, dropna=True)

- level위치 또는 열이름 지정
- level : int, str, list, default= -1
- dropna : bool, default True

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html

#### 예1. 1차 레벨을 가진 데이터프레임

In [94]:
df = pd.DataFrame([[0, 1], [2, 3]],
                  index=['cat', 'dog'],
                  columns=['weight', 'height'])
df

weight  height
cat       0       1
dog       2       3

In [95]:
df.stack()   # 스택하면 시리즈 --> 데이터프레임

cat  weight    0
     height    1
dog  weight    2
     height    3
dtype: int64

In [96]:
df.stack(level=0)

cat  weight    0
     height    1
dog  weight    2
     height    3
dtype: int64

#### 예2. 다중레벨을 갖는 데이터프레임

In [97]:
multicol1 = pd.MultiIndex.from_tuples([('weight', 'kg'),
                                       ('weight', 'pounds')])
df2 = pd.DataFrame([[1, 2], [2, 4]],
                                    index=['cat', 'dog'],
                                    columns=multicol1)
df2

weight       
        kg pounds
cat      1      2
dog      2      4

In [98]:
df2.stack()

weight
cat kg           1
    pounds       2
dog kg           2
    pounds       4

In [99]:
df2.stack(level=0)

kg  pounds
cat weight   1       2
dog weight   2       4

In [100]:
df2.stack(level=[0,1])

cat  weight  kg        1
             pounds    2
dog  weight  kg        2
             pounds    4
dtype: int64

#### 예3. 열인덱스 이름을 갖는 데이터프레임

In [103]:
df2.columns.names = ['C1','C2']
df2

C1  weight       
C2      kg pounds
cat      1      2
dog      2      4

In [104]:
df2.stack(level='C1')

C2          kg  pounds
    C1                
cat weight   1       2
dog weight   2       4

In [105]:
df2.stack(level=['C2','C1'])

     C2      C1    
cat  kg      weight    1
     pounds  weight    2
dog  kg      weight    2
     pounds  weight    4
dtype: int64

### 7. 다중인덱스의 레벨 교환 : swaplevel()

[형식] DataFrame.swaplevel(i=- 2, j=- 1, axis=0)

- i, j : int or str
    - Levels of the indices to be swapped. Can pass level name as string.

- axis : 0 or ‘index’, 1 or ‘columns', default=0
    - The axis to swap levels on
    - 0 or‘index’ for row-wise
    - 1 or ‘columns’ for column-wise

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.swaplevel.html

In [106]:
df = pd.DataFrame({"Grade": ["A", "B", "A", "C"]},
                  index=[
                      ["Final exam", "Final exam", "Coursework", "Coursework"],
                      ["History", "Geography", "History", "Geography"],
                      ["January", "February", "March", "April"],],)
df

Grade
Final exam History   January      A
           Geography February     B
Coursework History   March        A
           Geography April        C

In [107]:
df.swaplevel()

Grade
Final exam January  History       A
           February Geography     B
Coursework March    History       A
           April    Geography     C

In [108]:
df.swaplevel(0,1)

Grade
History   Final exam January      A
Geography Final exam February     B
History   Coursework March        A
Geography Coursework April        C

In [109]:
df.swaplevel(0,2)

Grade
January  History   Final exam     A
February Geography Final exam     B
March    History   Coursework     A
April    Geography Coursework     C

### [정리] 다중인덱스의 접근 방법

- 인덱스가 하나가 아니므로 묶어서(튜플로) 전달
- 열 접근 : df[(튜플)]
- 행 접근 : df.loc[(튜플)]
- 참고. df.iloc[]은 정수위치로 접근하여 다중인덱스에 구애받지 않음

### 문제.

#### 1. 다음과 같이 다중인덱스를 갖는 데이터프레임을 생성하시오.

- 행인덱스 레벨 = 2
- 열인덱스 레벨 = 2
- 데이터 크기는 (6,4)이며 값은 (0,1) 사이의 난수를 갖음
- 인덱스는 MultiIndex를 생성하는 방법을 사용

In [ ]:
df2 = df.copy()

#### 2. df의 'A'열을 출력하시오.

In [ ]:
df2.loc[('F,id1'),('B','c1')]=20
df2

#### 3. df의 'F'행을 출력하시오.

#### 4. df의 'A'열의 'C1'열을 출력하시오.

#### 5. df의 'M'행의  'id1'행을 출력하시오.

#### 6. df의 ('M', 'id1')행 'A'열을 출력하시오.

#### 7. df의 ('M', 'id1')행 ('A','C1')열 요소를 출력하시오.

#### 8. df의 4행 4열의 요소를 출력하시오.

#### 9. df의 4행 4열의 요소를 10으로 변경하시오.

-----

### 8. 다중인덱스의 행/열 추가

In [127]:
data = np.round(np.random.rand(6, 4), 2)
columns = pd.MultiIndex.from_product([['A','B'],['C1','C2']],
                                   names=['cidx1','cidx2'])
index = pd.MultiIndex.from_product([['M','F'],['id1','id2','id3']],
                                    names=['ridx1','ridx2'])
df = pd.DataFrame(data=data, index=index, columns=columns)
df

cidx1           A           B      
cidx2          C1    C2    C1    C2
ridx1 ridx2                        
M     id1    0.01  0.83  0.98  0.70
      id2    0.18  0.51  0.58  0.79
      id3    0.61  0.22  0.46  0.88
F     id1    0.49  0.72  0.49  0.71
      id2    0.50  0.84  0.19  0.77
      id3    0.97  0.86  0.78  0.99

In [128]:
df2 = df.copy()

#### 값입력을 위한 위치 지정 실수?

In [116]:
df2.loc[('F,id1'),('B','c1')]=20
df2

cidx1           A           B            
cidx2          C1    C2    C1    C2    c1
ridx1 ridx2                              
M     id1    0.22  0.22  0.57  0.45   NaN
      id2    0.97  0.68  0.09  0.06   NaN
      id3    0.49  0.88  0.98  0.62   NaN
F     id1    0.54  0.85  0.74  0.48   NaN
      id2    0.68  0.61  0.71  0.47   NaN
      id3    0.46  0.91  0.14  0.23   NaN
F,id1         NaN   NaN   NaN   NaN  20.0

In [126]:
df2 = df2.drop(columns=('B','c1'))
df2

KeyError: ('B', 'c1')

#### 각 행의 총합을 마지막 열로 추가

In [129]:
df2[('Row', 'Sum')]=df2.sum(axis=1)
df2

cidx1           A           B         Row
cidx2          C1    C2    C1    C2   Sum
ridx1 ridx2                              
M     id1    0.01  0.83  0.98  0.70  2.52
      id2    0.18  0.51  0.58  0.79  2.06
      id3    0.61  0.22  0.46  0.88  2.17
F     id1    0.49  0.72  0.49  0.71  2.41
      id2    0.50  0.84  0.19  0.77  2.30
      id3    0.97  0.86  0.78  0.99  3.60

#### 각 열의 총합을 마지막 행으로 추가

In [131]:
# 행과 열을 모두 지정해야 함
df2.loc[('Col', 'Sum'), :]=df2.sum(axis=0)
df2

cidx1           A           B          Row
cidx2          C1    C2    C1    C2    Sum
ridx1 ridx2                               
M     id1    0.01  0.83  0.98  0.70   2.52
      id2    0.18  0.51  0.58  0.79   2.06
      id3    0.61  0.22  0.46  0.88   2.17
F     id1    0.49  0.72  0.49  0.71   2.41
      id2    0.50  0.84  0.19  0.77   2.30
      id3    0.97  0.86  0.78  0.99   3.60
Col   Sum    5.52  7.96  6.96  9.68  30.12

### 9. 다중인덱스 정렬

### 1) sort_index()

[형식] sort_index(*, axis=0, level=None, ascending=True, inplace=False,)

- 행/열 인덱스 기준으로 정렬
- 기본 정렬 방식 : 오름차순 정렬
- 내림차순 : ascending=Flase 설정

####  행인덱스 정렬

In [132]:
df

cidx1           A           B      
cidx2          C1    C2    C1    C2
ridx1 ridx2                        
M     id1    0.01  0.83  0.98  0.70
      id2    0.18  0.51  0.58  0.79
      id3    0.61  0.22  0.46  0.88
F     id1    0.49  0.72  0.49  0.71
      id2    0.50  0.84  0.19  0.77
      id3    0.97  0.86  0.78  0.99

In [133]:
df.sort_index()

cidx1           A           B      
cidx2          C1    C2    C1    C2
ridx1 ridx2                        
F     id1    0.49  0.72  0.49  0.71
      id2    0.50  0.84  0.19  0.77
      id3    0.97  0.86  0.78  0.99
M     id1    0.01  0.83  0.98  0.70
      id2    0.18  0.51  0.58  0.79
      id3    0.61  0.22  0.46  0.88

In [134]:
df.sort_index(ascending=False)

cidx1           A           B      
cidx2          C1    C2    C1    C2
ridx1 ridx2                        
M     id3    0.61  0.22  0.46  0.88
      id2    0.18  0.51  0.58  0.79
      id1    0.01  0.83  0.98  0.70
F     id3    0.97  0.86  0.78  0.99
      id2    0.50  0.84  0.19  0.77
      id1    0.49  0.72  0.49  0.71

In [135]:
df.sort_index(level=1)

cidx1           A           B      
cidx2          C1    C2    C1    C2
ridx1 ridx2                        
F     id1    0.49  0.72  0.49  0.71
M     id1    0.01  0.83  0.98  0.70
F     id2    0.50  0.84  0.19  0.77
M     id2    0.18  0.51  0.58  0.79
F     id3    0.97  0.86  0.78  0.99
M     id3    0.61  0.22  0.46  0.88

#### 열인덱스 기준으로 정렬

In [136]:
df.sort_index(axis=1, ascending=False)

cidx1           B           A      
cidx2          C2    C1    C2    C1
ridx1 ridx2                        
M     id1    0.70  0.98  0.83  0.01
      id2    0.79  0.58  0.51  0.18
      id3    0.88  0.46  0.22  0.61
F     id1    0.71  0.49  0.72  0.49
      id2    0.77  0.19  0.84  0.50
      id3    0.99  0.78  0.86  0.97

In [137]:
df.sort_index(axis=1, level=1, ascending=False)

cidx1           B     A     B     A
cidx2          C2    C2    C1    C1
ridx1 ridx2                        
M     id1    0.70  0.83  0.98  0.01
      id2    0.79  0.51  0.58  0.18
      id3    0.88  0.22  0.46  0.61
F     id1    0.71  0.72  0.49  0.49
      id2    0.77  0.84  0.19  0.50
      id3    0.99  0.86  0.78  0.97

### 2) sort_values()

[형식] sort_values(by, *, axis=0, ascending=True, inplace=False, )

- 특정 컬럼 값을 기준으로 정렬
- by = 특정컬럼
    - 특정컬럼이 다중인덱스 일 경우 컬럼명을 튜플로 전달

#### df의 A.C1 컬럼을 기준으로 정렬

In [138]:
df.sort_values(by=('A','C1'))

cidx1           A           B      
cidx2          C1    C2    C1    C2
ridx1 ridx2                        
M     id1    0.01  0.83  0.98  0.70
      id2    0.18  0.51  0.58  0.79
F     id1    0.49  0.72  0.49  0.71
      id2    0.50  0.84  0.19  0.77
M     id3    0.61  0.22  0.46  0.88
F     id3    0.97  0.86  0.78  0.99

In [139]:
df.sort_values(by='A')

ValueError: The column label 'A' is not unique.
For a multi-index, the label must be a tuple with elements corresponding to each level.

-----------